"/": "Welcome#index"
"/zadania/nowe": "Exercises#newform"
"/zadania/utworz": "Exercises#create"
"/zadania/moje": "Exercises#userslist"
"/zadania/edytuj": "Exercises#edit"
"/zadania/zapisz": "Exercises#save"
"/zadania/podglad": "Exercises#show"
"/zadania": "Exercises#index"
"/kategorie": "Categories#index"
"/kategorie/nowa": "Categories#newform"
"/kategorie/utworz": "Categories#create"
"/uzytkownik": "Users#index"
"/uzytkownik/nowy": "Users#newform"
"/uzytkownik/utworz": "Users#create"
"/uzytkownik/zaloguj": "Users#login"
"/uzytkownik/wyloguj": "Users#logout"
